import { Camera, CameraOff, Mic, MicOff, Phone, PhoneOff, RefreshCw, Volume2, VolumeX } from "lucide-react";
import { useEffect, useRef, useState } from "react";
export default function CallScreen({ call,status,partnerName,localStream,remoteStream,muted,cameraOn,speakerOn,isIncoming,onAccept,onDecline,onEnd,onToggleMute,onToggleCamera,onToggleSpeaker,onSwitchCamera,error }) {
 const localVideoRef=useRef(null),remoteVideoRef=useRef(null),remoteAudioRef=useRef(null); const [seconds,setSeconds]=useState(0);
 useEffect(()=>{if(localVideoRef.current)localVideoRef.current.srcObject=localStream},[localStream]);
 useEffect(()=>{if(remoteVideoRef.current)remoteVideoRef.current.srcObject=remoteStream;if(remoteAudioRef.current){remoteAudioRef.current.srcObject=remoteStream;remoteAudioRef.current.muted=!speakerOn}},[remoteStream,speakerOn]);
 useEffect(()=>{if(status!=="connected")return;const t=setInterval(()=>setSeconds(v=>v+1),1000);return()=>clearInterval(t)},[status]);
 const time=`${String(Math.floor(seconds/60)).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`;
 const text=isIncoming?`Incoming ${call.type} call`:status==="connected"?time:status==="reconnecting"?"Reconnecting...":status==="connecting"?"Connecting...":"Ringing...";
 return <div className="fixed inset-0 z-[200] bg-slate-950 text-white" role="dialog" aria-modal="true"><audio ref={remoteAudioRef} autoPlay />
 {call.type==="video"&&<><video ref={remoteVideoRef} autoPlay playsInline className="absolute inset-0 h-full w-full object-cover"/><video ref={localVideoRef} autoPlay muted playsInline className="absolute right-4 top-4 z-10 h-40 w-28 rounded-2xl border border-white/30 bg-black object-cover shadow-2xl sm:h-52 sm:w-36"/></>}
 <div className="relative z-20 flex min-h-full flex-col items-center justify-between bg-gradient-to-b from-black/35 via-transparent to-black/65 px-5 py-10"><div className="text-center"><p className="text-xs tracking-[.35em]">TOGETHER</p><h2 className="mt-5 text-3xl font-bold">{partnerName}</h2><p className="mt-2">{text}</p>{error&&<p className="mt-2 max-w-sm text-sm text-red-300">{error}</p>}</div>
 {call.type==="audio"&&<div className="flex h-36 w-36 items-center justify-center rounded-full border-4 border-pink-300 bg-gradient-to-br from-rose-400 to-pink-600 text-5xl font-bold shadow-2xl">{partnerName[0]?.toUpperCase()}</div>}
 {isIncoming?<div className="flex gap-12"><button onClick={onDecline} className="flex flex-col items-center gap-2"><span className="flex h-16 w-16 items-center justify-center rounded-full bg-red-500"><PhoneOff/></span><span>Decline</span></button><button onClick={onAccept} className="flex flex-col items-center gap-2"><span className="flex h-16 w-16 items-center justify-center rounded-full bg-green-500"><Phone fill="currentColor"/></span><span>Accept</span></button></div>:<div className="flex flex-wrap items-center justify-center gap-3 rounded-3xl bg-black/30 p-4 backdrop-blur"><button onClick={onToggleMute} className={`flex h-14 w-14 items-center justify-center rounded-full transition ${muted?"animate-pulse bg-red-500":"bg-white/15"}`}>{muted?<MicOff/>:<Mic/>}</button><button onClick={onToggleSpeaker} className="flex h-14 w-14 items-center justify-center rounded-full bg-white/15">{speakerOn?<Volume2/>:<VolumeX/>}</button>{call.type==="video"&&<><button onClick={onToggleCamera} className="flex h-14 w-14 items-center justify-center rounded-full bg-white/15">{cameraOn?<Camera/>:<CameraOff/>}</button><button onClick={onSwitchCamera} className="flex h-14 w-14 items-center justify-center rounded-full bg-white/15"><RefreshCw/></button></>}<button onClick={onEnd} className="flex h-16 w-16 items-center justify-center rounded-full bg-red-500"><PhoneOff/></button></div>}</div></div>;
}
