import { useEffect, useState } from "react";
import { ArrowLeft, Headphones, MapPin, Play, Save, Timer, Video } from "lucide-react";
import { Link } from "react-router-dom";
import { useAuth } from "../contexts/AuthContext";
import { supabase } from "../services/supabase";

export default function MoreTogether(){
 const {user}=useAuth(); const [settings,setSettings]=useState({anniversary_date:"",watch_url:"",watch_position:0,watch_playing:false,music_url:"",music_position:0,music_playing:false,latitude:null,longitude:null,location_updated_at:null}); const [saving,setSaving]=useState(false);
 useEffect(()=>{if(!user)return; supabase.from("together_sync").select("*").limit(1).maybeSingle().then(({data})=>data&&setSettings(data)); const c=supabase.channel("together-sync").on("postgres_changes",{event:"*",schema:"public",table:"together_sync"},({new:n})=>n&&setSettings(n)).subscribe(); return()=>supabase.removeChannel(c)},[user]);
 async function save(patch){setSaving(true);const next={...settings,...patch,updated_by:user.id,updated_at:new Date().toISOString()};const {data,error}=await supabase.from("together_sync").upsert({...next,id:settings.id||"00000000-0000-0000-0000-000000000001"}).select().single();if(!error)setSettings(data);setSaving(false)}
 function shareLocation(){navigator.geolocation?.getCurrentPosition(p=>save({latitude:p.coords.latitude,longitude:p.coords.longitude,location_updated_at:new Date().toISOString()}),()=>alert("Location permission was denied."),{enableHighAccuracy:true})}
 const days=settings.anniversary_date?Math.max(0,Math.ceil((new Date(settings.anniversary_date)-new Date())/86400000)):null;
 return <div className="min-h-screen bg-[#fff7f9] pb-24"><header className="bg-gradient-to-r from-rose-500 to-pink-500 px-5 py-6 text-white"><div className="mx-auto flex max-w-6xl items-center gap-4"><Link to="/dashboard" className="rounded-full bg-white/20 p-2"><ArrowLeft/></Link><div><h1 className="text-2xl font-bold">More Together</h1><p className="text-sm text-rose-100">Synchronized activities for both of you</p></div></div></header><main className="mx-auto grid max-w-6xl gap-5 px-5 py-8 md:grid-cols-2">
 <Card icon={Timer} title="Anniversary countdown"><input type="date" value={settings.anniversary_date||""} onChange={e=>setSettings(s=>({...s,anniversary_date:e.target.value}))} className="w-full rounded-xl border p-3"/><button onClick={()=>save({anniversary_date:settings.anniversary_date})} className="mt-3 rounded-xl bg-rose-500 px-4 py-2 text-white"><Save className="mr-2 inline" size={16}/>Save</button>{days!==null&&<p className="mt-4 text-2xl font-bold text-rose-500">{days===0?"Today ❤️":`${days} days to go`}</p>}</Card>
 <Card icon={Video} title="Watch together"><input placeholder="Paste a video URL" value={settings.watch_url||""} onChange={e=>setSettings(s=>({...s,watch_url:e.target.value}))} className="w-full rounded-xl border p-3"/><div className="mt-3 flex gap-2"><button onClick={()=>save({watch_url:settings.watch_url,watch_playing:!settings.watch_playing})} className="rounded-xl bg-violet-500 px-4 py-2 text-white"><Play className="mr-2 inline" size={16}/>{settings.watch_playing?"Pause":"Play"}</button></div><p className="mt-2 text-xs text-slate-500">Both accounts receive the same URL and play/pause state in real time.</p></Card>
 <Card icon={Headphones} title="Listen together"><input placeholder="Paste a song or playlist URL" value={settings.music_url||""} onChange={e=>setSettings(s=>({...s,music_url:e.target.value}))} className="w-full rounded-xl border p-3"/><button onClick={()=>save({music_url:settings.music_url,music_playing:!settings.music_playing})} className="mt-3 rounded-xl bg-blue-500 px-4 py-2 text-white"><Play className="mr-2 inline" size={16}/>{settings.music_playing?"Pause":"Play"}</button></Card>
 <Card icon={MapPin} title="Live location"><button onClick={shareLocation} className="rounded-xl bg-green-500 px-4 py-2 text-white"><MapPin className="mr-2 inline" size={16}/>Share my current location</button>{settings.latitude&&<><p className="mt-4 text-sm">Latest shared coordinates:</p><a className="text-rose-500 underline" target="_blank" rel="noreferrer" href={`https://www.google.com/maps?q=${settings.latitude},${settings.longitude}`}>Open in Maps</a></>}</Card>
 </main>{saving&&<div className="fixed bottom-24 right-5 rounded-full bg-slate-900 px-4 py-2 text-sm text-white">Syncing...</div>}</div>
}
function Card({icon:Icon,title,children}){return <section className="rounded-3xl border border-rose-100 bg-white p-6 shadow-sm"><div className="mb-5 flex items-center gap-3"><span className="rounded-2xl bg-rose-100 p-3 text-rose-500"><Icon/></span><h2 className="text-xl font-bold text-slate-800">{title}</h2></div>{children}</section>}
